name: 'Setup Script'
description: 'Installs the necessary libraries and pulls cache'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
    - name: Setup Libraries
      shell: bash
      run: sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Upgrade Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.79.0
        components: rustfmt, clippy, rustc
        target: x86_64-unknown-linux-musl
        cache: true
