name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
    checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.3
      with:
        shared-key: rust_cache
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: auguwu/clippy-action@1.4.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}

  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.3
      with: 
        shared-key: rust_cache
    - name: Build
      run: cargo build --release
    - name: Save Artifact
      uses: manoadamro/rust-release@v1
      with:
        owner: PCOffline
        repo: https://github.com/PCOffline/rummikub
        token: ${{ secrets.GITHUB_TOKEN }}
      
